CREATE DATABASE ss4ep5;
USE ss4ep5;

CREATE TABLE Student(
    MaSV VARCHAR(10) PRIMARY KEY,
    HoTen VARCHAR(50) NOT NULL
);

CREATE TABLE Subject(
    MaMH VARCHAR(10) PRIMARY KEY,
    TenMH VARCHAR(50),
    SoTinChi INT CHECK(SoTinChi > 0)
);

CREATE TABLE Teacher(
    MaGV INT AUTO INCREMENT PRIMARY KEY,
    HoTen VARCHAR(10) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE
)

ALTER TABLE Subject
ADD COLUMN MaGV INT;

ALTER TABLE Subject
ADD CONSTRAINT fk_subject_teacher
FOREIGN KEY (MaGV) REFERENCES Teacher(MaGV)